[mysqld]
port=3307
basedir=D:/app/MySQL/MySQL Server 8.0/
datadir=C:/Users/28576/Desktop/MediCare/.mysql-local/data
character-set-server=utf8mb4
collation-server=utf8mb4_unicode_ci
lower_case_table_names=1
default-storage-engine=INNODB
max_connections=151
secure-file-priv=""
[client]
port=3307
